### ISSUE TITLE
(question) Mod support

### ISSUE THREAD

**Issue by Mythilily** [Lanboost/TModLoader_LansToggleableBuffs#1]
Do you have plans to support other mods like Thorium and Grealm?

**Comment by Lanboost** [comment]
Copied from our discord chat:

> Yes, I've seen it, I ahve been thinking at supporting thorium at least as that and calamity is the mods I have been planning to play, however for now I it is distant in the future, however last night I sad down and started on a new "better" way which will enable the mod to support all potion buffs independently of mod/version etc, basically reading through the items and if the items applies a buff it will be added to the "Togglebuff" window. 
> 
> This however can and will lead to overpowered buffs like calamities immunity potion to be added, so how this will be handled is not decided on yet.
> 
> So to conclude, sorry for not responding, I'm working on a long term solution but it might take some time, hopefully I can get a first version that doesnt cover the edge-cases out later tonight or tomorrow
> 
> Regards
> Lan

**Comment by Lanboost** [comment]
As with the latest update this feature is now available. Closing over and out
