### ISSUE TITLE
(Issue) Selecting Buffs Outside of Window

### ISSUE THREAD

**Issue by DemonGamesXIII** [Lanboost/TModLoader_LansToggleableBuffs#2]
Hey Lan! Ran into an issue the other day where if the player has too many mods that add in buffs, the window for selecting the buffs doesn't properly adjust and causes certain buffs to be unselectable.

(I know I already posted it on the Terraria forum, but it would probably be easier to read it here)

The issue:
![image](https://user-images.githubusercontent.com/25541106/68324924-0526b400-008e-11ea-8212-000d08efa6d4.png)

**Comment by Lanboost** [comment]
This issue is hopefully fixed by a badly done scroll panel, if this introduces any other errors or the issue persist, feel free to open a new ticket.

Closing this issue.

Thanks for reporting this issue
//Lan
