### ISSUE TITLE
How do I even use this mod

### ISSUE THREAD

**Issue by Endy444** [Lanboost/TModLoader_LansToggleableBuffs#4]
I installed it but I have no clue how to open the UI as there's nothing that tells me how. Help?

**Comment by Lanboost** [comment]
Open keybinds (Dont have the game installed but should be menu->settings->hotkeys or something similar) scroll down and at the bottom there should be hotkeys for mods.

In that list this mod should have an unbound hotkey. Set it to something, store and open the window by pressing it
